import test from 'node:test';
import assert from 'node:assert/strict';
import { roleHotkeys } from '../src/roleHotkeys.js';
test('role hints exclude occupied posts and gunner depth charges', () => {
  const members = [{ playerId: 'gunner', station: 'flak' }, { playerId: 'two', station: 'cannon' }, { playerId: 'three', station: 'lookout' }];
  const bridge = roleHotkeys({ role: 'bridge', playerId: 'captain', members });
  assert.ok(bridge.some(([k]) => k === 'W'));
  assert.ok(!bridge.some(([k]) => ['F', 'C', 'O', 'A', '⇧A'].includes(k)));
  const flak = roleHotkeys({ role: 'flak', playerId: 'gunner', members });
  assert.ok(!flak.some(([k]) => k === 'W'));
  assert.ok(flak.some(([k]) => k === 'A'));
  const lookout = roleHotkeys({ role: 'lookout', depthChargesReady: false });
  assert.ok(lookout.some(([k]) => k === 'Z'));
  assert.ok(!lookout.some(([k]) => k === 'W'));
  assert.equal(lookout.filter(([k]) => k === 'C').length, 1);
  assert.equal(lookout.filter(([k]) => k === 'F').length, 1);
  assert.ok(!lookout.some(([k]) => k.includes('⇧C') || k.includes('⇧F')));
  const occupiedLookout = roleHotkeys({ role: 'lookout', playerId: 'look', members });
  assert.ok(occupiedLookout.some(([k, label]) => k === 'C' && label.includes('Zustimmung')));
  assert.ok(occupiedLookout.some(([k, label]) => k === 'F' && label.includes('Zustimmung')));
});
